FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest pytest-cov pytest-mock httpx

# COPY . .

# Set PYTHONPATH so Python can find your modules
ENV PYTHONPATH=/app
ENV DATABASE_URL=sqlite:///:memory:

# Run the tests
CMD pytest -v tests/