# GitHub Actions workflow for Python services in monorepo
# Runs tests for feedback, member, and organization services

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-feedback:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/services/feedback
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
      - name: Run tests
        run: pytest tests

  test-member:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/services/member
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
      - name: Run tests
        run: pytest tests

  test-organization:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/services/organization
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
      - name: Run tests
        run: pytest || echo "No tests found for organization service."
